/**
 * Broad part-code pattern library for common through-hole and SMD components.
 * Evaluated after exact DB lookup; order matters (specific patterns before general).
 * Keys are tested against normalised part codes (uppercase, no spaces/dashes).
 */

export const COMMON_PART_PATTERNS = [
  // ── Resistors (additional families) ─────────────────────────────
  { pattern: /^WSL[A-Z0-9]{2,}/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'Vishay', description: 'SMD Power Resistor' } },
  { pattern: /^CRCW0(201|402|603|805|1206)/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'Vishay', description: 'SMD Thick Film Resistor' } },
  { pattern: /^AC0(402|603|805|1206)/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'Yageo', description: 'SMD Chip Resistor' } },
  { pattern: /^RTT0(402|603|805|1206)/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'KOA', description: 'SMD Chip Resistor' } },
  { pattern: /^MCR0(1|2|3)/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'Rohm', description: 'SMD Chip Resistor' } },
  { pattern: /^RN[0-9]{2}[A-Z]/, result: { category: 'Resistors', subcategory: 'SMD', description: 'SMD Chip Resistor Array' } },
  { pattern: /^RK73[HB]/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'KOA', description: 'SMD Thick Film Resistor' } },
  { pattern: /^RMCF/, result: { category: 'Resistors', subcategory: 'SMD', description: 'SMD Chip Resistor' } },
  { pattern: /^MRS/, result: { category: 'Resistors', subcategory: 'SMD', manufacturer: 'Rohm', description: 'SMD Metal Oxide Resistor' } },

  // ── Capacitors (additional) ───────────────────────────────────
  { pattern: /^GCM[0-9]/, result: { category: 'Capacitors', subcategory: 'MLCC', manufacturer: 'Murata', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^GRT[0-9]/, result: { category: 'Capacitors', subcategory: 'MLCC', manufacturer: 'Murata', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^DE1/, result: { category: 'Capacitors', subcategory: 'MLCC', manufacturer: 'Murata', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^UMK/, result: { category: 'Capacitors', subcategory: 'MLCC', manufacturer: 'TDK', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^CGA[0-9]/, result: { category: 'Capacitors', subcategory: 'MLCC', manufacturer: 'Kemet', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^CL32/, result: { category: 'Capacitors', subcategory: 'MLCC', package: '1210', manufacturer: 'Samsung', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^CL03/, result: { category: 'Capacitors', subcategory: 'MLCC', package: '0201', manufacturer: 'Samsung', description: 'MLCC Ceramic Capacitor' } },
  { pattern: /^TAJ[A-Z0-9]/, result: { category: 'Capacitors', subcategory: 'Tantalum', manufacturer: 'AVX/Kyocera', description: 'Tantalum Capacitor' } },
  { pattern: /^T491[A-Z0-9]/, result: { category: 'Capacitors', subcategory: 'Tantalum', manufacturer: 'AVX', description: 'SMD Tantalum Capacitor' } },
  { pattern: /^TPS[A-Z0-9]/, result: { category: 'Capacitors', subcategory: 'Polymer', manufacturer: 'AVX', description: 'Polymer Tantalum Capacitor' } },
  { pattern: /^293D/, result: { category: 'Capacitors', subcategory: 'Tantalum', manufacturer: 'Vishay', description: 'Tantalum Capacitor' } },
  { pattern: /^TMK/, result: { category: 'Capacitors', subcategory: 'Film', manufacturer: 'TDK', description: 'Film Capacitor' } },
  { pattern: /^B325/, result: { category: 'Capacitors', subcategory: 'Film', manufacturer: 'EPCOS/TDK', description: 'Film Capacitor' } },
  { pattern: /^UWT/, result: { category: 'Capacitors', subcategory: 'Electrolytic', manufacturer: 'Nichicon', description: 'SMD Aluminium Electrolytic' } },
  { pattern: /^UUX/, result: { category: 'Capacitors', subcategory: 'Electrolytic', manufacturer: 'Nichicon', description: 'Aluminium Electrolytic' } },
  { pattern: /^EEV/, result: { category: 'Capacitors', subcategory: 'Electrolytic', manufacturer: 'Panasonic', description: 'Aluminium Electrolytic' } },
  { pattern: /^EEE/, result: { category: 'Capacitors', subcategory: 'Electrolytic', manufacturer: 'Panasonic', description: 'Aluminium Electrolytic' } },
  { pattern: /^RVT/, result: { category: 'Capacitors', subcategory: 'Electrolytic', manufacturer: 'Rubycon', description: 'Aluminium Electrolytic' } },
  { pattern: /^16SV/, result: { category: 'Capacitors', subcategory: 'Electrolytic', description: 'Aluminium Electrolytic' } },
  { pattern: /^25SV/, result: { category: 'Capacitors', subcategory: 'Electrolytic', description: 'Aluminium Electrolytic' } },

  // ── Inductors / ferrite ─────────────────────────────────────────
  { pattern: /^LQH[0-9]/, result: { category: 'Inductors', subcategory: 'SMD', manufacturer: 'Murata', description: 'SMD Power Inductor' } },
  { pattern: /^LPS[0-9]/, result: { category: 'Inductors', subcategory: 'SMD', manufacturer: 'Murata', description: 'SMD Power Inductor' } },
  { pattern: /^SRN[0-9]/, result: { category: 'Inductors', subcategory: 'SMD', manufacturer: 'Bourns', description: 'SMD Shielded Inductor' } },
  { pattern: /^SRP[0-9]/, result: { category: 'Inductors', subcategory: 'SMD', manufacturer: 'Bourns', description: 'SMD Power Inductor' } },
  { pattern: /^CD54/, result: { category: 'Inductors', subcategory: 'SMD', description: 'SMD Power Inductor' } },
  { pattern: /^CD43/, result: { category: 'Inductors', subcategory: 'SMD', description: 'SMD Power Inductor' } },
  { pattern: /^BLM[0-9]/, result: { category: 'Inductors', subcategory: 'Ferrite Core', manufacturer: 'Murata', description: 'Ferrite Bead' } },
  { pattern: /^MPZ[0-9]/, result: { category: 'Inductors', subcategory: 'Ferrite Core', manufacturer: 'TDK', description: 'Ferrite Bead' } },
  { pattern: /^MI[0-9]{3}/, result: { category: 'Inductors', subcategory: 'Ferrite Core', description: 'Ferrite Bead' } },
  { pattern: /^WE-LH/, result: { category: 'Inductors', subcategory: 'SMD', manufacturer: 'Wurth', description: 'SMD Power Inductor' } },

  // ── Diodes (specific before 1Nxx general) ───────────────────────
  { pattern: /^BAT54/, result: { category: 'Diodes', subcategory: 'Schottky', package: 'SOT-23', description: 'Schottky Diode Array' } },
  { pattern: /^BAT4[68]/, result: { category: 'Diodes', subcategory: 'Schottky', description: 'Small Signal Schottky' } },
  { pattern: /^BAT85/, result: { category: 'Diodes', subcategory: 'Schottky', description: 'Small Signal Schottky' } },
  { pattern: /^LL4148/, result: { category: 'Diodes', subcategory: 'Small Signal', package: 'LL-34', description: 'SMD Small Signal Diode' } },
  { pattern: /^LL34/, result: { category: 'Diodes', subcategory: 'Small Signal', description: 'SMD Small Signal Diode' } },
  { pattern: /^MMSZ/, result: { category: 'Diodes', subcategory: 'Zener', package: 'SOD-123', description: 'SMD Zener Diode' } },
  { pattern: /^MM3Z/, result: { category: 'Diodes', subcategory: 'Zener', package: 'SOD-323', description: 'SMD Zener Diode' } },
  { pattern: /^SMAJ/, result: { category: 'Diodes', subcategory: 'TVS', package: 'SMA', description: 'TVS Diode' } },
  { pattern: /^SMCJ/, result: { category: 'Diodes', subcategory: 'TVS', package: 'SMC', description: 'TVS Diode' } },
  { pattern: /^P6SMB/, result: { category: 'Diodes', subcategory: 'TVS', package: 'SMB', description: 'TVS Diode' } },
  { pattern: /^ES1[A-Z]?/, result: { category: 'Diodes', subcategory: 'Fast Recovery', package: 'SMA', description: 'Ultrafast Rectifier' } },
  { pattern: /^ES2[A-Z]?/, result: { category: 'Diodes', subcategory: 'Fast Recovery', package: 'SMB', description: 'Ultrafast Rectifier' } },
  { pattern: /^ES3[A-Z]?/, result: { category: 'Diodes', subcategory: 'Fast Recovery', description: 'Ultrafast Rectifier' } },
  { pattern: /^FR1[0-9]{2}/, result: { category: 'Diodes', subcategory: 'Fast Recovery', description: 'Fast Recovery Rectifier' } },
  { pattern: /^UF1[0-9]{2}/, result: { category: 'Diodes', subcategory: 'Fast Recovery', description: 'Ultrafast Recovery Rectifier' } },
  { pattern: /^SB1[0-9]{2}/, result: { category: 'Diodes', subcategory: 'Schottky', description: 'Schottky Barrier Rectifier' } },
  { pattern: /^SK1[0-9]{2}/, result: { category: 'Diodes', subcategory: 'Schottky', description: 'Schottky Barrier Rectifier' } },
  { pattern: /^M7$/, result: { category: 'Diodes', subcategory: 'Rectifier', package: 'SMA', description: '1A Rectifier Diode M7' } },
  { pattern: /^S1[A-M]$/, result: { category: 'Diodes', subcategory: 'Rectifier', package: 'SMA', description: 'SMD Rectifier Diode' } },
  { pattern: /^S2[A-M]$/, result: { category: 'Diodes', subcategory: 'Rectifier', package: 'SMB', description: 'SMD Rectifier Diode' } },
  { pattern: /^S3[A-M]$/, result: { category: 'Diodes', subcategory: 'Rectifier', description: 'SMD Rectifier Diode' } },
  { pattern: /^1N4148/, result: { category: 'Diodes', subcategory: 'Small Signal', description: 'Small Signal Switching Diode' } },
  { pattern: /^1N914/, result: { category: 'Diodes', subcategory: 'Small Signal', description: 'Small Signal Switching Diode' } },
  { pattern: /^1N400[1-7]/, result: { category: 'Diodes', subcategory: 'Rectifier', package: 'DO-41', description: 'General Purpose Rectifier 1A' } },
  { pattern: /^1N540[0-8]/, result: { category: 'Diodes', subcategory: 'Rectifier', package: 'DO-201', description: 'General Purpose Rectifier 3A' } },
  { pattern: /^1N581[79]/, result: { category: 'Diodes', subcategory: 'Schottky', description: 'Schottky Barrier Rectifier' } },
  { pattern: /^1N582[02]/, result: { category: 'Diodes', subcategory: 'Schottky', description: 'Schottky Barrier Rectifier' } },
  { pattern: /^DB3/, result: { category: 'Diodes', subcategory: 'Trigger Diode', description: 'DIAC / Trigger Diode' } },
  { pattern: /^DB4/, result: { category: 'Diodes', subcategory: 'Trigger Diode', description: 'DIAC / Trigger Diode' } },
  { pattern: /^GBU/, result: { category: 'Diodes', subcategory: 'Bridge Rectifier', description: 'Bridge Rectifier' } },
  { pattern: /^KBP/, result: { category: 'Diodes', subcategory: 'Bridge Rectifier', description: 'Bridge Rectifier' } },
  { pattern: /^KBU/, result: { category: 'Diodes', subcategory: 'Bridge Rectifier', description: 'Bridge Rectifier' } },
  { pattern: /^DF10/, result: { category: 'Diodes', subcategory: 'Bridge Rectifier', description: 'Bridge Rectifier' } },

  // ── LEDs / photodiodes ──────────────────────────────────────────
  { pattern: /^WS2812/, result: { category: 'Diodes', subcategory: 'LED', description: 'Addressable RGB LED' } },
  { pattern: /^SK6812/, result: { category: 'Diodes', subcategory: 'LED', description: 'Addressable RGB LED' } },
  { pattern: /^APA102/, result: { category: 'Diodes', subcategory: 'LED', description: 'Addressable RGB LED' } },
  { pattern: /^LTL1/, result: { category: 'Diodes', subcategory: 'LED', description: 'LED Indicator' } },
  { pattern: /^LTST/, result: { category: 'Diodes', subcategory: 'LED', manufacturer: 'Lite-On', description: 'SMD LED' } },
  { pattern: /^KP[0-9]/, result: { category: 'Diodes', subcategory: 'LED', description: 'LED Indicator' } },

  // ── Transistors (BJT before general 2N) ─────────────────────────
  { pattern: /^MMBT[0-9]{2,3}/, result: { category: 'Transistors', subcategory: 'BJT', package: 'SOT-23', description: 'SMD BJT' } },
  { pattern: /^MMBC[0-9]{2,3}/, result: { category: 'Transistors', subcategory: 'BJT', package: 'SOT-23', description: 'SMD BJT' } },
  { pattern: /^S8050/, result: { category: 'Transistors', subcategory: 'BJT NPN', package: 'SOT-23', description: 'NPN BJT' } },
  { pattern: /^S8550/, result: { category: 'Transistors', subcategory: 'BJT PNP', package: 'SOT-23', description: 'PNP BJT' } },
  { pattern: /^SS8050/, result: { category: 'Transistors', subcategory: 'BJT NPN', package: 'SOT-23', description: 'NPN BJT' } },
  { pattern: /^SS8550/, result: { category: 'Transistors', subcategory: 'BJT PNP', package: 'SOT-23', description: 'PNP BJT' } },
  { pattern: /^BC8[0-9]{2}/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'Small Signal NPN BJT' } },
  { pattern: /^BC5[0-9]{2}/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'Small Signal NPN BJT' } },
  { pattern: /^BC3[0-9]{2}/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'Power NPN BJT' } },
  { pattern: /^BC2[0-9]{2}/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'Small Signal PNP BJT' } },
  { pattern: /^BD1[0-9]{2}/, result: { category: 'Transistors', subcategory: 'BJT NPN', package: 'TO-126', description: 'Power NPN BJT' } },
  { pattern: /^BD2[0-9]{2}/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'Power PNP BJT' } },
  { pattern: /^TIP12[027]/, result: { category: 'Transistors', subcategory: 'Darlington NPN', package: 'TO-220', description: 'Darlington NPN' } },
  { pattern: /^TIP4[12]/, result: { category: 'Transistors', subcategory: 'BJT NPN', package: 'TO-220', description: 'Power NPN BJT' } },
  { pattern: /^TIP3[12]/, result: { category: 'Transistors', subcategory: 'BJT', package: 'TO-220', description: 'Power BJT' } },
  { pattern: /^2N2222/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'NPN BJT' } },
  { pattern: /^2N2907/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'PNP BJT' } },
  { pattern: /^2N3055/, result: { category: 'Transistors', subcategory: 'BJT NPN', package: 'TO-220', description: 'Power NPN BJT' } },
  { pattern: /^2N3904/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'General Purpose NPN' } },
  { pattern: /^2N3906/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'General Purpose PNP' } },
  { pattern: /^2N5401/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'High Voltage PNP' } },
  { pattern: /^2N5551/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'High Voltage NPN' } },
  { pattern: /^MJE340/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'High Voltage NPN' } },
  { pattern: /^MJE350/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'High Voltage PNP' } },
  { pattern: /^KSA[0-9]/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'Audio NPN BJT' } },
  { pattern: /^KSC[0-9]/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'Audio NPN BJT' } },
  { pattern: /^KSA1220/, result: { category: 'Transistors', subcategory: 'BJT PNP', description: 'Audio PNP BJT' } },
  { pattern: /^KSC2073/, result: { category: 'Transistors', subcategory: 'BJT NPN', description: 'Audio NPN BJT' } },

  // ── MOSFETs / IGBT (STPS before STP) ────────────────────────────
  { pattern: /^IRL[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'Logic-Level N-Ch MOSFET' } },
  { pattern: /^IRF[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'TO-220', description: 'N-Ch Power MOSFET' } },
  { pattern: /^IRFZ[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'TO-220', description: 'N-Ch Power MOSFET' } },
  { pattern: /^IRLML[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'SOT-23', description: 'Logic-Level MOSFET' } },
  { pattern: /^AO340[01]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'SOT-23', manufacturer: 'Alpha & Omega', description: 'SMD MOSFET' } },
  { pattern: /^AO44[0-9]{2}/, result: { category: 'Transistors', subcategory: 'Power MOSFET', manufacturer: 'Alpha & Omega', description: 'SMD MOSFET' } },
  { pattern: /^SI23[0-9]{2}/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'SOT-23', manufacturer: 'Vishay', description: 'SMD MOSFET' } },
  { pattern: /^SI23[0-9]{3}/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'SOT-23', description: 'SMD MOSFET' } },
  { pattern: /^FQP[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'TO-220', description: 'N-Ch Power MOSFET' } },
  { pattern: /^FDP[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'N-Ch Power MOSFET' } },
  { pattern: /^FDS[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'N-Ch Power MOSFET' } },
  { pattern: /^BSS[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'SOT-23', description: 'SMD N-Ch MOSFET' } },
  { pattern: /^BSP[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', package: 'SOT-23', description: 'SMD P-Ch MOSFET' } },
  { pattern: /^DMG[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'SMD MOSFET' } },
  { pattern: /^DMP[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'SMD P-Ch MOSFET' } },
  { pattern: /^IPD[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', manufacturer: 'Infineon', description: 'Power MOSFET' } },
  { pattern: /^IPA[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', manufacturer: 'Infineon', description: 'Power MOSFET' } },
  { pattern: /^FQD[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'N-Ch Power MOSFET' } },
  { pattern: /^FDD[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'P-Ch Power MOSFET' } },
  { pattern: /^BUK[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', manufacturer: 'Nexperia', description: 'Power MOSFET' } },
  { pattern: /^ZXMN[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', manufacturer: 'Diodes Inc', description: 'SMD MOSFET' } },
  { pattern: /^ZXMP[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', manufacturer: 'Diodes Inc', description: 'SMD P-Ch MOSFET' } },
  { pattern: /^2SK[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'N-Ch MOSFET' } },
  { pattern: /^2SJ[0-9]/, result: { category: 'Transistors', subcategory: 'Power MOSFET', description: 'P-Ch MOSFET' } },
  { pattern: /^IKW[0-9]/, result: { category: 'Transistors', subcategory: 'IGBT', manufacturer: 'Infineon', description: 'IGBT' } },
  { pattern: /^IRG[0-9]/, result: { category: 'Transistors', subcategory: 'IGBT', manufacturer: 'Infineon', description: 'IGBT' } },
  { pattern: /^FGA[0-9]/, result: { category: 'Transistors', subcategory: 'IGBT', manufacturer: 'Fairchild', description: 'IGBT' } },
  { pattern: /^GW[0-9]{2}/, result: { category: 'Transistors', subcategory: 'IGBT', description: 'IGBT' } },

  // ── Voltage regulators / references ─────────────────────────────
  { pattern: /^AMS1117/, result: { category: 'ICs', subcategory: 'LDO Regulator', package: 'SOT-223', description: 'LDO Voltage Regulator' } },
  { pattern: /^LM1117/, result: { category: 'ICs', subcategory: 'LDO Regulator', description: 'LDO Voltage Regulator' } },
  { pattern: /^LD1117/, result: { category: 'ICs', subcategory: 'LDO Regulator', description: 'LDO Voltage Regulator' } },
  { pattern: /^AP2112/, result: { category: 'ICs', subcategory: 'LDO Regulator', manufacturer: 'Diodes Inc', description: 'LDO Regulator' } },
  { pattern: /^MIC520[59]/, result: { category: 'ICs', subcategory: 'LDO Regulator', manufacturer: 'Microchip', description: 'LDO Regulator' } },
  { pattern: /^MIC5219/, result: { category: 'ICs', subcategory: 'LDO Regulator', manufacturer: 'Microchip', description: 'LDO Regulator' } },
  { pattern: /^HT7333/, result: { category: 'ICs', subcategory: 'LDO Regulator', description: '3.3V LDO Regulator' } },
  { pattern: /^HT78[0-9]{2}/, result: { category: 'ICs', subcategory: 'LDO Regulator', description: 'LDO Regulator' } },
  { pattern: /^SPX3819/, result: { category: 'ICs', subcategory: 'LDO Regulator', description: 'LDO Regulator' } },
  { pattern: /^NCP1117/, result: { category: 'ICs', subcategory: 'LDO Regulator', manufacturer: 'ON Semi', description: 'LDO Regulator' } },
  { pattern: /^LM317/, result: { category: 'ICs', subcategory: 'Linear Regulator', description: 'Adjustable Voltage Regulator' } },
  { pattern: /^LM337/, result: { category: 'ICs', subcategory: 'Linear Regulator', description: 'Adjustable Negative Regulator' } },
  { pattern: /^LM2596/, result: { category: 'ICs', subcategory: 'Buck Converter', description: 'Step-Down Switching Regulator' } },
  { pattern: /^LM2576/, result: { category: 'ICs', subcategory: 'Buck Converter', description: 'Step-Down Switching Regulator' } },
  { pattern: /^MP1584/, result: { category: 'ICs', subcategory: 'Buck Converter', manufacturer: 'MPS', description: 'Step-Down Converter' } },
  { pattern: /^XL4015/, result: { category: 'ICs', subcategory: 'Buck Converter', description: 'Step-Down DC-DC Module IC' } },
  { pattern: /^XL6009/, result: { category: 'ICs', subcategory: 'Boost Converter', description: 'Step-Up DC-DC Module IC' } },
  { pattern: /^TL431/, result: { category: 'ICs', subcategory: 'Voltage Reference', description: 'Adjustable Shunt Regulator' } },
  { pattern: /^TL432/, result: { category: 'ICs', subcategory: 'Voltage Reference', description: 'Adjustable Shunt Regulator' } },
  { pattern: /^L78L/, result: { category: 'ICs', subcategory: 'Linear Regulator', manufacturer: 'STMicro', description: 'Positive Voltage Regulator' } },
  { pattern: /^L79L/, result: { category: 'ICs', subcategory: 'Linear Regulator', manufacturer: 'STMicro', description: 'Negative Voltage Regulator' } },

  // ── Analog / timing ICs ─────────────────────────────────────────
  { pattern: /^NE555/, result: { category: 'ICs', subcategory: 'Timer', description: '555 Timer IC' } },
  { pattern: /^LM555/, result: { category: 'ICs', subcategory: 'Timer', description: '555 Timer IC' } },
  { pattern: /^TLC555/, result: { category: 'ICs', subcategory: 'Timer', description: 'CMOS 555 Timer' } },
  { pattern: /^ICM7555/, result: { category: 'ICs', subcategory: 'Timer', description: 'CMOS 555 Timer' } },
  { pattern: /^LM358/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Dual Op-Amp' } },
  { pattern: /^LM324/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Quad Op-Amp' } },
  { pattern: /^TL072/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Dual JFET Op-Amp' } },
  { pattern: /^TL082/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Dual JFET Op-Amp' } },
  { pattern: /^NE5532/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Dual Low-Noise Op-Amp' } },
  { pattern: /^OP07/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Precision Op-Amp' } },
  { pattern: /^OP27/, result: { category: 'ICs', subcategory: 'Op-Amp', description: 'Low-Noise Op-Amp' } },
  { pattern: /^LM393/, result: { category: 'ICs', subcategory: 'Comparator', description: 'Dual Comparator' } },
  { pattern: /^LM339/, result: { category: 'ICs', subcategory: 'Comparator', description: 'Quad Comparator' } },
  { pattern: /^ULN2003/, result: { category: 'ICs', subcategory: 'Darlington Driver', description: 'Darlington Transistor Array' } },
  { pattern: /^ULN2803/, result: { category: 'ICs', subcategory: 'Darlington Driver', description: 'Darlington Transistor Array' } },
  { pattern: /^L293D/, result: { category: 'ICs', subcategory: 'Motor Driver', description: 'Dual H-Bridge Motor Driver' } },
  { pattern: /^L298N/, result: { category: 'ICs', subcategory: 'Motor Driver', description: 'Dual H-Bridge Motor Driver' } },
  { pattern: /^A4988/, result: { category: 'ICs', subcategory: 'Stepper Driver', manufacturer: 'Allegro', description: 'Stepper Motor Driver' } },
  { pattern: /^DRV8825/, result: { category: 'ICs', subcategory: 'Stepper Driver', manufacturer: 'TI', description: 'Stepper Motor Driver' } },
  { pattern: /^TMC2208/, result: { category: 'ICs', subcategory: 'Stepper Driver', manufacturer: 'Trinamic', description: 'Stepper Motor Driver' } },
  { pattern: /^SN754410/, result: { category: 'ICs', subcategory: 'Motor Driver', description: 'Dual H-Bridge Driver' } },

  // ── Microcontrollers / SoC ──────────────────────────────────────
  { pattern: /^ESP32/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Espressif', description: 'WiFi/BT MCU' } },
  { pattern: /^ESP8266/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Espressif', description: 'WiFi MCU' } },
  { pattern: /^ESP01/, result: { category: 'Modules', subcategory: 'WiFi Module', manufacturer: 'Espressif', description: 'ESP8266 WiFi Module' } },
  { pattern: /^STM32[FHLG][0-9]/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'STMicro', description: 'ARM Cortex-M MCU' } },
  { pattern: /^ATMEGA[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'AVR MCU' } },
  { pattern: /^ATTINY[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'AVR Tiny MCU' } },
  { pattern: /^ATMEGA328/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'AVR MCU 32KB' } },
  { pattern: /^PIC16F[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'PIC MCU' } },
  { pattern: /^PIC18F[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'PIC MCU' } },
  { pattern: /^PIC12F[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'PIC MCU' } },
  { pattern: /^RP2040/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Raspberry Pi', description: 'Dual-Core MCU' } },
  { pattern: /^RP2350/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Raspberry Pi', description: 'Dual-Core MCU' } },
  { pattern: /^NRF52[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Nordic', description: 'BLE MCU' } },
  { pattern: /^NRF24[0-9]+/, result: { category: 'ICs', subcategory: 'RF Transceiver', manufacturer: 'Nordic', description: '2.4GHz RF' } },
  { pattern: /^GD32F[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'GigaDevice', description: 'ARM MCU' } },
  { pattern: /^CH32V[0-9]+/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'WCH', description: 'RISC-V MCU' } },
  { pattern: /^SAMD21/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'ARM Cortex-M0+ MCU' } },
  { pattern: /^ATSAMD21/, result: { category: 'ICs', subcategory: 'Microcontroller', manufacturer: 'Microchip', description: 'ARM Cortex-M0+ MCU' } },

  // ── Interface / memory / RTC ────────────────────────────────────
  { pattern: /^CH340/, result: { category: 'ICs', subcategory: 'USB-UART', manufacturer: 'WCH', description: 'USB to Serial Bridge' } },
  { pattern: /^CP210[0-9]/, result: { category: 'ICs', subcategory: 'USB-UART', manufacturer: 'Silicon Labs', description: 'USB to UART Bridge' } },
  { pattern: /^FT232/, result: { category: 'ICs', subcategory: 'USB-UART', manufacturer: 'FTDI', description: 'USB to UART Bridge' } },
  { pattern: /^PL2303/, result: { category: 'ICs', subcategory: 'USB-UART', description: 'USB to Serial Bridge' } },
  { pattern: /^SP3232/, result: { category: 'ICs', subcategory: 'RS-232 Driver', description: 'RS-232 Transceiver' } },
  { pattern: /^SP3485/, result: { category: 'ICs', subcategory: 'RS-485 Transceiver', description: 'RS-485 Transceiver' } },
  { pattern: /^W5500/, result: { category: 'ICs', subcategory: 'Ethernet', manufacturer: 'Wiznet', description: 'Ethernet Controller' } },
  { pattern: /^ENC28J60/, result: { category: 'ICs', subcategory: 'Ethernet', manufacturer: 'Microchip', description: 'Ethernet Controller' } },
  { pattern: /^AT24C[0-9]+/, result: { category: 'ICs', subcategory: 'EEPROM', manufacturer: 'Microchip', description: 'I2C EEPROM' } },
  { pattern: /^24C[0-9]+/, result: { category: 'ICs', subcategory: 'EEPROM', description: 'I2C EEPROM' } },
  { pattern: /^24LC[0-9]+/, result: { category: 'ICs', subcategory: 'EEPROM', description: 'I2C EEPROM' } },
  { pattern: /^W25Q[0-9]+/, result: { category: 'ICs', subcategory: 'Flash', manufacturer: 'Winbond', description: 'SPI NOR Flash' } },
  { pattern: /^AT25[0-9]+/, result: { category: 'ICs', subcategory: 'Flash', description: 'SPI Flash' } },
  { pattern: /^MX25[0-9]+/, result: { category: 'ICs', subcategory: 'Flash', manufacturer: 'Macronix', description: 'SPI NOR Flash' } },
  { pattern: /^DS1307/, result: { category: 'ICs', subcategory: 'RTC', manufacturer: 'Maxim', description: 'I2C Real-Time Clock' } },
  { pattern: /^DS3231/, result: { category: 'ICs', subcategory: 'RTC', manufacturer: 'Maxim', description: 'Precision RTC' } },
  { pattern: /^PCF8563/, result: { category: 'ICs', subcategory: 'RTC', description: 'I2C Real-Time Clock' } },
  { pattern: /^PCF8523/, result: { category: 'ICs', subcategory: 'RTC', description: 'I2C Real-Time Clock' } },

  // ── Sensors ─────────────────────────────────────────────────────
  { pattern: /^LM75/, result: { category: 'Sensors', subcategory: 'Temperature', description: 'I2C Temperature Sensor' } },
  { pattern: /^TMP102/, result: { category: 'Sensors', subcategory: 'Temperature', manufacturer: 'TI', description: 'I2C Temperature Sensor' } },
  { pattern: /^TMP36/, result: { category: 'Sensors', subcategory: 'Temperature', description: 'Analog Temperature Sensor' } },
  { pattern: /^DHT11/, result: { category: 'Sensors', subcategory: 'Humidity / Temp', description: 'Humidity/Temperature Sensor' } },
  { pattern: /^DHT22/, result: { category: 'Sensors', subcategory: 'Humidity / Temp', description: 'Humidity/Temperature Sensor' } },
  { pattern: /^MPU6050/, result: { category: 'Sensors', subcategory: 'IMU', manufacturer: 'InvenSense', description: '6-Axis IMU' } },
  { pattern: /^MPU9250/, result: { category: 'Sensors', subcategory: 'IMU', description: '9-Axis IMU' } },
  { pattern: /^BMP180/, result: { category: 'Sensors', subcategory: 'Pressure', manufacturer: 'Bosch', description: 'Barometric Pressure Sensor' } },
  { pattern: /^BMP280/, result: { category: 'Sensors', subcategory: 'Pressure', manufacturer: 'Bosch', description: 'Barometric Pressure Sensor' } },
  { pattern: /^BME280/, result: { category: 'Sensors', subcategory: 'Humidity / Temp', manufacturer: 'Bosch', description: 'Environmental Sensor' } },
  { pattern: /^ADXL345/, result: { category: 'Sensors', subcategory: 'Accelerometer', manufacturer: 'Analog Devices', description: '3-Axis Accelerometer' } },
  { pattern: /^LIS3DH/, result: { category: 'Sensors', subcategory: 'Accelerometer', manufacturer: 'ST', description: '3-Axis Accelerometer' } },
  { pattern: /^HMC5883/, result: { category: 'Sensors', subcategory: 'Magnetometer', description: '3-Axis Magnetometer' } },
  { pattern: /^QMC5883/, result: { category: 'Sensors', subcategory: 'Magnetometer', description: '3-Axis Magnetometer' } },
  { pattern: /^TCRT5000/, result: { category: 'Sensors', subcategory: 'Optical', description: 'Reflective Optical Sensor' } },
  { pattern: /^HC-SR[0-9]+/, result: { category: 'Sensors', subcategory: 'Ultrasonic', description: 'Ultrasonic Distance Sensor Module' } },
  { pattern: /^OV7670/, result: { category: 'Sensors', subcategory: 'Camera', description: 'CMOS Camera Module' } },
  { pattern: /^OV2640/, result: { category: 'Sensors', subcategory: 'Camera', description: 'CMOS Camera Module' } },

  // ── Crystals / oscillators ────────────────────────────────────────
  { pattern: /^ABM[0-9]/, result: { category: 'Crystals', subcategory: 'Crystal', manufacturer: 'Abracon', description: 'Crystal Resonator' } },
  { pattern: /^ABLS[0-9]/, result: { category: 'Crystals', subcategory: 'Crystal', manufacturer: 'Abracon', description: 'Crystal Resonator' } },
  { pattern: /^ECS[0-9]{3}/, result: { category: 'Crystals', subcategory: 'Crystal', manufacturer: 'ECS', description: 'Crystal Resonator' } },
  { pattern: /^X49/, result: { category: 'Crystals', subcategory: 'HC-49/S', description: 'Crystal Resonator' } },
  { pattern: /^ABLNO/, result: { category: 'Crystals', subcategory: 'Oscillator', manufacturer: 'Abracon', description: 'MEMS Oscillator' } },
  { pattern: /^ASE/, result: { category: 'Crystals', subcategory: 'Oscillator', manufacturer: 'Abracon', description: 'Crystal Oscillator' } },
  { pattern: /^8[0-9]{3}F/, result: { category: 'Crystals', subcategory: 'Crystal', description: '8MHz Crystal (common marking)' } },

  // ── Relays ──────────────────────────────────────────────────────
  { pattern: /^G6K/, result: { category: 'Relays', subcategory: 'Relay', manufacturer: 'Omron', description: 'Signal Relay' } },
  { pattern: /^G5V/, result: { category: 'Relays', subcategory: 'Relay', manufacturer: 'Omron', description: 'Signal Relay' } },
  { pattern: /^G2R/, result: { category: 'Relays', subcategory: 'Relay', manufacturer: 'Omron', description: 'Power Relay' } },
  { pattern: /^HJR/, result: { category: 'Relays', subcategory: 'Relay', description: 'Signal Relay' } },
  { pattern: /^SLA/, result: { category: 'Relays', subcategory: 'Relay', description: 'Power Relay' } },

  // ── Connectors / mechanical ─────────────────────────────────────
  { pattern: /^KF[0-9]{3}/, result: { category: 'Connectors', subcategory: 'Terminal Block', description: 'Screw Terminal Block' } },
  { pattern: /^DG[0-9]{3}/, result: { category: 'Connectors', subcategory: 'Terminal Block', description: 'Screw Terminal Block' } },
  { pattern: /^B3F/, result: { category: 'Switches', subcategory: 'Tactile', manufacturer: 'Omron', description: 'Tactile Switch' } },
  { pattern: /^TS[0-9]/, result: { category: 'Switches', subcategory: 'Tactile', description: 'Tactile Switch' } },
  { pattern: /^SS-/, result: { category: 'Switches', subcategory: 'Slide', description: 'Slide Switch' } },
  { pattern: /^MSKE/, result: { category: 'Switches', subcategory: 'Toggle', description: 'Toggle Switch' } },
  { pattern: /^USB-A/, result: { category: 'Connectors', subcategory: 'USB', description: 'USB Connector' } },
  { pattern: /^USB-C/, result: { category: 'Connectors', subcategory: 'USB', description: 'USB Type-C Connector' } },
  { pattern: /^DC-0(59|55)/, result: { category: 'Connectors', subcategory: 'DC Jack', description: 'DC Power Jack' } },
  { pattern: /^DC005/, result: { category: 'Connectors', subcategory: 'DC Jack', description: 'DC Power Jack' } },
  { pattern: /^JST/, result: { category: 'Connectors', subcategory: 'JST', manufacturer: 'JST', description: 'Wire-to-Board Connector' } },
  { pattern: /^PH-?[0-9]/, result: { category: 'Connectors', subcategory: 'JST', description: 'JST PH Connector' } },
  { pattern: /^XH-?[0-9]/, result: { category: 'Connectors', subcategory: 'JST', description: 'JST XH Connector' } },
  { pattern: /^HDR[0-9]/, result: { category: 'Connectors', subcategory: 'Pin Header', description: 'Pin Header' } },
  { pattern: /^DS10[0-9]{2}/, result: { category: 'Connectors', subcategory: 'IC Socket', description: 'DIP IC Socket' } },
  { pattern: /^FR4/, result: { category: 'Mechanical', subcategory: 'PCB / Board', description: 'FR4 PCB Material' } },
  { pattern: /^PCB/, result: { category: 'Mechanical', subcategory: 'PCB / Board', description: 'Printed Circuit Board' } },
];
