#!/usr/bin/env node
// Generates src/styles/tokens.css from the Bugra design tokens (docs/design/bugra/tokens.json) and
// the app's additions (docs/design/added-tokens.json). No color is typed by hand anywhere else:
// `npm run check:colors` rejects hex and rgb() outside this generated file.
//   node tools/tokens/build-tokens.mjs          write the file
//   node tools/tokens/build-tokens.mjs --check  fail when the file is out of date
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));
const bugra = JSON.parse(fs.readFileSync(path.join(root, 'docs/design/bugra/tokens.json'), 'utf8'));
const added = JSON.parse(fs.readFileSync(path.join(root, 'docs/design/added-tokens.json'), 'utf8'));
const out = path.join(root, 'src/styles/tokens.css');

const ref = (v) => String(v).replace(/\{([a-z0-9-]+)\}/g, 'var(--$1)');
const lines = (entries) => entries.map(([k, v]) => `  --${k}: ${v};`).join('\n');

const dark = [];
const light = [];
for (const t of bugra.color.tokens) {
  if (typeof t.value === 'string') {
    dark.push([t.name, ref(t.value)]);
  } else {
    dark.push([t.name, ref(t.value.dark)]);
    if (t.value.light !== t.value.dark) light.push([t.name, ref(t.value.light)]);
  }
}
for (const t of bugra.shadow.tokens) {
  dark.push([t.name, t.value.dark]);
  light.push([t.name, t.value.light]);
}

const fixed = [];
fixed.push(['font-ui', bugra.type.families.ui]);
fixed.push(['font-mono', bugra.type.families.mono]);
for (const g of bugra.type.groups) {
  for (const s of g.styles) {
    fixed.push([`text-${s.name}-size`, s.fontSize]);
    fixed.push([`text-${s.name}-line`, s.lineHeight]);
    fixed.push([`text-${s.name}-weight`, String(s.fontWeight)]);
    if (s.letterSpacing) fixed.push([`text-${s.name}-tracking`, s.letterSpacing]);
  }
}
for (const group of ['spacing', 'radius', 'size', 'opacity', 'duration', 'easing', 'zIndex']) {
  for (const t of bugra[group].tokens) fixed.push([t.name, t.value]);
}
for (const group of ['size', 'zIndex']) {
  for (const t of added[group] || []) fixed.push([t.name, t.value]);
}

const css = `/* Generated by tools/tokens/build-tokens.mjs from docs/design/bugra/tokens.json (Bugra v${bugra.version})
   and docs/design/added-tokens.json. Do not edit: change the JSON and run \`npm run tokens\`. */

:root {
${lines(fixed)}
}

/* Dark is the default theme. */
:root,
:root[data-theme='dark'] {
  color-scheme: dark;
${lines(dark)}
}

/* Light is derived; it overrides only what differs. */
:root[data-theme='light'] {
  color-scheme: light;
${lines(light)}
}
`;

if (process.argv.includes('--check')) {
  // Line endings do not count: a Windows checkout with core.autocrlf has CRLF on disk.
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : '';
  if (current !== css) {
    console.error('src/styles/tokens.css is out of date: run `npm run tokens`.');
    process.exit(1);
  }
  console.log('tokens.css is up to date');
} else {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, css);
  console.log('wrote', path.relative(root, out));
}
